[pytest]
asyncio_mode = strict
markers =
    asyncio: mark a test as asyncio
    integration: mark a test as integration test
testpaths = tests src_python/tests
norecursedirs = 99_unsortiert external 5d private-gpt-main node_modules
addopts = --ignore=99_unsortiert/ --ignore=private-gpt-main/ --ignore=external/
