#!/usr/bin/env python3
"""Dimension 4: Ökonomische Intelligenz.

Fragenkatalog basierend auf partizipativer Ökonomie,
Commons-Theorie und nachhaltigen Wirtschaftsmodellen.
"""

ECONOMICS_QUESTIONS = [
    {
        "id": "econ_participation",
        "question": "Wie wichtig ist Ihnen Mitbestimmung in wirtschaftlichen Entscheidungen (am Arbeitsplatz, in der Gemeinde)?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Albert, M., & Hahnel, R. (1991). The political economy of participatory economics.",
        "bibtex_key": "albert1991parecon",
        "sub_dimension": "Participatory Economics",
    },
    {
        "id": "econ_commons",
        "question": "Wie wichtig ist Ihnen gemeinschaftliches Eigentum an Ressourcen (Wasser, Land, Wissen)?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Ostrom, E. (1990). Governing the commons: The evolution of institutions for collective action.",
        "bibtex_key": "ostrom1990commons",
        "sub_dimension": "Commons Management",
    },
    {
        "id": "econ_degrowth",
        "question": "Inwieweit stimmen Sie zu, dass endloses Wirtschaftswachstum auf einem endlichen Planeten unmöglich ist?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Stimme überhaupt nicht zu",
            "Stimme eher nicht zu",
            "Neutral",
            "Stimme eher zu",
            "Stimme voll zu",
        ],
        "required": True,
        "reference": "Kallis, G., Kostakis, V., Lange, S., Muraca, B., Paulson, S., & Schmelzer, M. (2018). Research on degrowth.",
        "bibtex_key": "kallis2018degrowth",
        "sub_dimension": "Degrowth & Sustainability",
    },
    {
        "id": "econ_cooperative",
        "question": "Wie attraktiv finden Sie Unternehmensformen wie Genossenschaften oder Kollektive?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht attraktiv",
            "Wenig attraktiv",
            "Mäßig attraktiv",
            "Attraktiv",
            "Sehr attraktiv",
        ],
        "required": True,
        "reference": "Rothschild-Whitt, J. (1979). The collectivist organization.",
        "bibtex_key": "rothschild1979collective",
        "sub_dimension": "Cooperative Economics",
    },
    {
        "id": "econ_universal_basic",
        "question": "Wie wichtig ist Ihnen das Konzept eines bedingungslosen Grundeinkommens?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Van Parijs, P., & Vanderborght, Y. (2017). Basic income: A radical proposal for a free society and a sane economy.",
        "bibtex_key": "vanparijs2017ubi",
        "sub_dimension": "Universal Basic Income",
    },
    {
        "id": "econ_local_economy",
        "question": "Wie wichtig ist es Ihnen, lokale Wirtschaftskreisläufe zu stärken?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Shuman, M. (2000). Going local: Creating self-reliant communities in a global age.",
        "bibtex_key": "shuman2000local",
        "sub_dimension": "Local Economics",
    },
    {
        "id": "econ_wealth_distribution",
        "question": "Wie wichtig ist Ihnen eine gerechtere Verteilung von Vermögen in der Gesellschaft?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Piketty, T. (2013). Le capital au XXIe siècle.",
        "bibtex_key": "piketty2013capital",
        "sub_dimension": "Wealth Distribution",
    },
    {
        "id": "econ_circular_economy",
        "question": "Wie wichtig ist Ihnen das Konzept der Kreislaufwirtschaft (Wiederverwertung, Reparatur statt Neukauf)?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Ellen MacArthur Foundation (2013). Towards the circular economy.",
        "bibtex_key": "macarthur2013circular",
        "sub_dimension": "Circular Economy",
    },
    {
        "id": "econ_solidarity_economy",
        "question": "Wie wichtig ist Ihnen solidarisches Wirtschaften (gegenseitige Hilfe, Tauschsysteme)?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": [
            "Überhaupt nicht wichtig",
            "Wenig wichtig",
            "Mäßig wichtig",
            "Wichtig",
            "Sehr wichtig",
        ],
        "required": True,
        "reference": "Laville, J.-L. (2010). The solidarity economy.",
        "bibtex_key": "laville2010solidarity",
        "sub_dimension": "Solidarity Economy",
    },
    {
        "id": "econ_financial_literacy",
        "question": "Wie gut verstehen Sie grundlegende wirtschaftliche Zusammenhänge (Zinsen, Inflation, Aktienmärkte)?",
        "type": "likert",
        "scale": [1, 2, 3, 4, 5],
        "labels": ["Sehr schlecht", "Eher schlecht", "Mittelmäßig", "Gut", "Sehr gut"],
        "required": True,
        "reference": "Lusardi, A., & Mitchell, O. S. (2014). The economic importance of financial literacy.",
        "bibtex_key": "lusardi2014financial",
        "sub_dimension": "Financial Literacy",
    },
]

SUB_DIMENSIONS = [
    "Participatory Economics",
    "Commons Management",
    "Degrowth & Sustainability",
    "Cooperative Economics",
    "Universal Basic Income",
    "Local Economics",
    "Wealth Distribution",
    "Circular Economy",
    "Solidarity Economy",
    "Financial Literacy",
]
