from playwright.sync_api import sync_playwright, expect
import os
import sys

def verify_a11y(page):
    print("Verifying accessibility improvements...")

    # Ensure verification directory exists
    os.makedirs("verification", exist_ok=True)

    # Note: This assumes the server is running at localhost:5173
    page.goto("http://localhost:5173/5d/docs/analysis/")

    # 1. Check citation bubbles have role="button" and aria-label
    # We need to wait for them to be generated by the useEffect
    # They are identified by having data-ref attribute on parent, but the bubble itself is a 'sup' tag

    # Find the first citation bubble
    # The parent has data-ref="...|..."
    # The bubble is a 'sup' inside it

    # Let's target any sup element that we expect to be a citation bubble
    # We can search for one that has role="button"

    # Wait for at least one citation bubble to appear
    citation_bubble = page.locator('sup[role="button"]').first
    expect(citation_bubble).to_be_visible(timeout=5000)

    # Check attributes
    expect(citation_bubble).to_have_attribute("tabindex", "0")

    aria_label = citation_bubble.get_attribute("aria-label")
    print(f"Found citation bubble with aria-label: {aria_label}")
    if not aria_label or not aria_label.startswith("Quellenverweis"):
        raise Exception(f"Citation bubble missing correct aria-label. Found: {aria_label}")

    title = citation_bubble.get_attribute("title")
    print(f"Found citation bubble with title: {title}")
    if not title or not title.startswith("Quelle öffnen"):
        raise Exception(f"Citation bubble missing correct title. Found: {title}")

    # 2. Check Dark Mode toggle aria-label
    # It starts as light mode, so label should be "Switch to dark mode"
    # The default state in App.jsx is: const [darkMode, setDarkMode] = useState(false);
    # So initially it is light mode, showing Moon icon, label "Switch to dark mode"

    dark_mode_btn = page.get_by_label("Switch to dark mode")
    expect(dark_mode_btn).to_be_visible()

    # Click it to toggle
    dark_mode_btn.click()

    # Now it should be dark mode, showing Sun icon, label "Switch to light mode"
    light_mode_btn = page.get_by_label("Switch to light mode")
    expect(light_mode_btn).to_be_visible()

    # Take screenshot
    page.screenshot(path="verification/a11y_check.png")
    print("Screenshot saved to verification/a11y_check.png")

    print("Accessibility verification passed!")

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            verify_a11y(page)
        except Exception as e:
            print(f"Verification failed: {e}")
            sys.exit(1)
        finally:
            browser.close()
