import datetime
import glob
import os
import shutil
import subprocess
import sys
from pathlib import Path


def run_step(command, description):
    """Runs a shell command and prints progress."""
    print(f"⏳ {description}...")
    try:
        result = subprocess.run(command, shell=True, check=True, capture_output=True, text=True)
        print(f"✅ {description} complete.")
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"❌ {description} failed!")
        print(f"Error: {e.stderr}")
        sys.exit(1)

def main():
    print("📦 Generating Evidence Package...")

    # Setup paths
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    package_dir = Path(f"outputs/evidence_package_{timestamp}")
    package_dir.mkdir(parents=True, exist_ok=True)

    # 1. Run Validation Study (IMP)
    # Ensure PYTHONPATH is set so scripts can import modules
    env = os.environ.copy()
    env["PYTHONPATH"] = os.getcwd()

    print("\n🚀 Running IMP Validation Study...")
    try:
        # Assuming imp_validation_study.py is in validation/ directory and runnable
        result = subprocess.run(
            [sys.executable, "validation/imp_validation_study.py"],
            capture_output=True,
            text=True,
            env=env
        )
        if result.returncode == 0:
            print("✅ IMP Validation Study complete.")
            # Save output log
            with open(package_dir / "validation_study.log", "w") as f:
                f.write(result.stdout)
        else:
            print("⚠️  IMP Validation Study finished with errors (check log).")
            print(result.stderr)

        # Copy Analysis Script
        shutil.copy("validation/imp_validation_study.py", package_dir / "imp_validation_study.py")
        print("  -> Copied Analysis Script: validation/imp_validation_study.py")

        # Move artifacts
        # (Assuming the script generates validation_report.json in current dir or output dir)
        # Adjust logic to find where the script actually outputs files
        for f in glob.glob("validation_report_*.json"):
             shutil.copy(f, package_dir / f)
             print(f"  -> Copied {f}")

        for f in glob.glob("outputs/*.png"):
             shutil.copy(f, package_dir / os.path.basename(f))
             print(f"  -> Copied {f}")

    except Exception as e:
        print(f"❌ Error running validation study: {e}")

    # 2. Run Research Scraper
    print("\n🚀 Running Research Scraper...")
    try:
        result = subprocess.run(
            [sys.executable, "5d_research_scraper.py"],
            capture_output=True,
            text=True,
            env=env
        )
        if result.returncode == 0:
             print("✅ Research Scraper complete.")
        else:
             print("⚠️  Research Scraper finished with errors.")
             print(result.stderr)

        if os.path.exists("5d_research_data.json"):
            shutil.copy("5d_research_data.json", package_dir / "5d_research_data.json")
            print("  -> Copied 5d_research_data.json")
        else:
            print("⚠️  5d_research_data.json not found.")

    except Exception as e:
        print(f"❌ Error running scraper: {e}")

    # 3. Generate Interpretation & Metrics MD
    # (Here we could parse the JSONs and generate the markdown files dynamically)
    # For now, just placeholder or copying if they exist
    print("\n📝 Generating Documentation...")

    # ... logic to parse validation_report.json and create INTERPRETATION.md ...

    with open(package_dir / "README.md", "w") as f:
        f.write(f"# Evidence Package {timestamp}\n\n")
        f.write("Generated by scripts/generate_evidence_package.py\n")
        f.write("## Contents\n")
        f.write("- validation_study.log: Output log of the validation study\n")
        f.write("- 5d_research_data.json: Scraped research data\n")
        f.write("- imp_validation_study.py: The script used for validation\n")

    print(f"\n📦 Package generated at: {package_dir}")

if __name__ == "__main__":
    main()
